# app/main.py

##################################################################
# Importing packages                                             #
##################################################################
from fastapi import FastAPI

from app.api.routers import scan_router

##################################################################
# APP settings                                                   #
##################################################################
app = FastAPI(
    title="Goldoak API version 0.8",
    description="With this API version you can query data generated by the Wazuh-Module."
)

@app.get("/")
async def read_root():
    return {"message": "Hello, World!"}

app.include_router(scan_router.router, prefix="/api/greenbone")


